name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: |
            #major:major,
            #minor:minor,
            #patch:patch,
            #fix:patch,
            bug:patch:Bug Fix,
            chore:patch:Chore,
            feat:patch:Feature,
            perf:patch:Performance,
            ci:patch:Continuous Integration,
            docs:patch:Documentation,
            style:patch:Code Style,
            refactor:patch:Refactoring,
            test:patch:Tests,
            preminor_upd:preminor:Pre Minor Update,
            minor_upd:minor:Minor Update,
            major_upd:major:Major Update